### PR TITLE
Add browser compatibility

### PR DESCRIPTION
**Pull request by politician**
CommonJS modules don't work natively in a browser, I have added a try/catch statement just so the CommonJS export is used only in supported environments.

### CODE REVIEW

**Comment by politician** [comment]
@fibo If you merge this PR, please do not forget to push the new version to NPM 🔥

**Comment by fibo** [comment]
Thank you very much for your contribution, I am declining it just because I am switching to support native ES6 export from current released version 3.

I was thinking about it, and yes now its time to move to next version.

**Comment by politician** [comment]
@fibo the new version still doesn't support being called from a browser (unless the browser supports ES6). Do you want me to submit the same PR against the commonJS version of v3?

**Comment by fibo** [comment]
I think it is ok to support only ES6 imports, since it is one row of code if someone needs to support older browsers can copy and paste the code.

Thanks again for reporting it. I am also happy if you use the package, I am using it for React web apps and it helps a lot with logic stuff. I hope it can help also other people.

**Pull request closed without merging**
